//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIT_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerTest
    {
        public int IdTestCase { get; set; }
        public int IdAnswer { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Testcase Testcase { get; set; }
    }
}
