//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIT_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MITEntities : DbContext
    {
        public MITEntities()
            : base("name=MITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AnswerTest> AnswerTests { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<Shape> Shapes { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Testcase> Testcases { get; set; }
    }
}
