//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIT_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shape
    {
        public int Id { get; set; }
        public Nullable<int> IdQuestion { get; set; }
        public Nullable<int> Type { get; set; }
        public string Text { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
